name: Firebase Deploy

on:
  push:
    branches:
      - main  # Ou outra branch que você queira usar

jobs:
  build:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g firebase-tools
        npm ci

    - name: Deploy to Firebase
      run: |
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
