[build]
  functions = "."

[[redirects]]
  from = "/adicionarLink"
  to = "/.netlify/functions/adicionarLink"
  status = 200

[[redirects]]
  from = "/recuperarLinks"
  to = "/.netlify/functions/recuperarLinks"
  status = 200
